app/currency/urls.py
from currency.views import (
    ContactUSCreateView,
    RateCreateView,
    RateDeleteView,
    RateDetailView,
    RateListView,
    RateUpdateView,
    SourceCreateView,
    SourceDeleteView,
    SourceDetailView,
    SourceListView,
    SourceUpdateView,
    )

from django.urls import path

app_name = 'currency'

urlpatterns = [
    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),
    path('source/list/', SourceListView.as_view(), name='source-list'),
    path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source-details'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
    path('contact_us/create/', ContactUSCreateView.as_view(), name='contact-us-create'),
    path('source/create/', SourceCreateView.as_view(), name='source-create'),
    path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
    path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),
]

app/settings/urls.py
from currency.views import (
    # index,
    IndexView,
    )

from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', index, name='index'),
    path('', IndexView.as_view(), name='index'),

    path('currency/', include('currency.urls')),

    path("__debug__/", include("debug_toolbar.urls")),
]

app/currency/models.py
from django.db import models


class Rate(models.Model):
    currency_type = models.CharField(max_length=5)
    sale = models.DecimalField(max_digits=5, decimal_places=2)
    buy = models.DecimalField(max_digits=5, decimal_places=2)
    source = models.CharField(max_length=64)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)


class ContactUS(models.Model):
    email_from = models.EmailField(max_length=320)
    subject = models.CharField(max_length=64)
    message = models.CharField(max_length=1024)
    created = models.DateTimeField(auto_now_add=True)


class Source(models.Model):
    source_name = models.CharField(max_length=64)
    source_url = models.URLField(max_length=256)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

app/currency/forms.py
from currency.models import ContactUS, Rate, Source

from django import forms


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'currency_type',
            'sale',
            'buy',
            'source',
        )


class ContactUSForm(forms.ModelForm):

    class Meta:
        model = ContactUS
        fields = (
            "subject",
            "message",
            )


class SourceForm(forms.ModelForm):

    class Meta:
        model = Source
        fields = (
            "source_name",
            "source_url",
            )

app/currency/views.py
from currency.forms import ContactUSForm, RateForm, SourceForm
from currency.models import ContactUS, Rate, Source

from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView


class IndexView(TemplateView):
    template_name = "index.html"


class RateListView(ListView):
    model = Rate
    template_name = "rate_list.html"


class RateDetailView(DetailView):
    model = Rate
    template_name = "rate_details.html"


class RateCreateView(CreateView):
    model = Rate
    form_class = RateForm
    template_name = "rate_create.html"
    success_url = reverse_lazy('currency:rate-list')


class RateUpdateView(UpdateView):
    model = Rate
    form_class = RateForm
    template_name = "rate_update.html"
    success_url = reverse_lazy('currency:rate-list')


class RateDeleteView(DeleteView):
    model = Rate
    template_name = "rate_delete.html"
    success_url = reverse_lazy('currency:rate-list')


class SourceListView(ListView):
    model = Source
    template_name = "source_list.html"


class SourceDetailView(DetailView):
    model = Source
    template_name = "source_details.html"


class SourceCreateView(CreateView):
    model = Source
    form_class = SourceForm
    template_name = "source_create.html"
    success_url = reverse_lazy('currency:source-list')


class SourceUpdateView(UpdateView):
    model = Source
    form_class = SourceForm
    template_name = "source_update.html"
    success_url = reverse_lazy('currency:source-list')


class SourceDeleteView(DeleteView):
    model = Source
    template_name = "source_delete.html"
    success_url = reverse_lazy('currency:source-list')


class ContactUSCreateView(CreateView):
    model = ContactUS
    form_class = ContactUSForm
    template_name = "contact_us_create.html"
    success_url = reverse_lazy('index')

app/currency/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% block main_content %}
    {% endblock main_content %}

</body>
</html>

app/currency/templates/base_table.html
<!DOCTYPE html>
<html lang="en">
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% block main_content_list %}
    {% endblock main_content_list %}

</body>
</html>

app/currency/templates/contact_us_create.html
{% extends "base.html" %}


{% block main_content %}

{{ massage }}
    
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Send </button>
</form>

{% endblock main_content %}

app/currency/templates/index.html
{% extends "base.html" %}


{% block main_content %}

<a href="{% url "currency:rate-list" %}"> Rate List </a>
<a href="{% url "currency:source-list" %}"> Source List </a>
<a href="{% url "currency:contact-us-create" %}"> Contact Us </a>

{% endblock main_content %}

app/currency/templates/rate_create.html
{% extends "base.html" %}


{% block main_content %}

{{ massage }}
    
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Send </button>
</form>

{% endblock main_content %}

app/currency/templates/rate_delete.html
{% extends "base.html" %}


{% block main_content %}

<form method="post">
    {% csrf_token %}
    <button type="submit"> Confirm </button>
</form>

{% endblock main_content %}

app/currency/templates/rate_details.html
{% extends "base_table.html" %}

{% block main_content_list %}

<h2>
    Rate Details
</h2>
<table>
    <tr>
        <th> ID </th>
        <th> Currency type </th>
        <th> Sale </th>
        <th> Buy </th>
        <th> Source </th>
        <th> Updated </th>
        <th> Created </th>
    </tr>
    <tr>
        <td> {{ object.id }} </td>
        <td> {{ object.currency_type }} </td>
        <td> {{ object.sale }} </td>
        <td> {{ object.buy }} </td>
        <td> {{ object.source }} </td>
        <td> {{ object.updated }} </td>
        <td> {{ object.created }} </td>
    </tr>
</table>

{% endblock main_content_list %}

app/currency/templates/rate_list.html
{% extends "base_table.html" %}


{% block main_content_list %}

<a href="{% url "currency:rate-create" %}"> Create Rate </a>

<h2>
    Rate List
</h2>
<table>
    <tr>
        <th> ID </th>
        <th> Currency type </th>
        <th> Sale </th>
        <th> Buy </th>
        <th> Source </th>
        <th> Updated </th>
        <th> Created </th>
    </tr>
    {% for rate in object_list %}
    <tr>
        <td> {{ rate.id }} </td>
        <td> {{ rate.currency_type }} </td>
        <td> {{ rate.sale }} </td>
        <td> {{ rate.buy }} </td>
        <td> {{ rate.source }} </td>
        <td> {{ rate.updated }} </td>
        <td> {{ rate.created }} </td>
        <td><a href="{% url "currency:rate-details" rate.id %}"> Details </a></td>
        <td><a href="{% url "currency:rate-update" rate.id %}"> Edit </a></td>
    </tr>
    {% endfor %}

</table>

{% endblock main_content_list %}

app/currency/templates/rate_update.html
{% extends "base.html" %}


{% block main_content %}

{{ massage }}
    
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Send </button>
</form>

<a href="{% url "currency:rate-delete" %}"> Delete </a>

{% endblock main_content %}

app/currency/templates/source_create.html
{% extends "base.html" %}


{% block main_content %}

{{ massage }}
    
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Send </button>
</form>

{% endblock main_content %}

app/currency/templates/source_delete.html
{% extends "base.html" %}


{% block main_content %}

<form method="post">
    {% csrf_token %}
    <button type="submit"> Confirm </button>
</form>

{% endblock main_content %}

app/currency/templates/source_details.html
{% extends "base_table.html" %}


{% block main_content_list %}

<h2>
  Source Details
</h2>
<table>
  <tr>
      <th> ID </th>
      <th> Source Name </th>
      <th> Source URL </th>
      <th> Updated </th>
      <th> Created </th>
  </tr>
  <tr>
      <td> {{ source.id }} </td>
      <td> {{ source.source_name }} </td>
      <td> {{ source.source_url }} </td>
      <td> {{ source.updated }} </td>
      <td> {{ source.created }} </td>
  </tr>
</table>

{% endblock main_content_list %}

app/currency/templates/source_list.html
{% extends "base_table.html" %}


{% block main_content_list %}

<a href="{% url "currency:source-create" %}"> Create Source </a>

<h2>
    Source List
</h2>
<table>
    <tr>
        <th> ID </th>
        <th> Source Name </th>
        <th> Source URL </th>
        <th> Updated </th>
        <th> Created </th>
    </tr>
    {% for source in source_list %}
    <tr>
        <td> {{ source.id }} </td>
        <td> {{ source.source_name }} </td>
        <td> {{ source.source_url }} </td>
        <td> {{ source.updated }} </td>
        <td> {{ source.created }} </td>
        <td><a href="{% url "currency:source-details" source.id %}"> Details </a></td>
        <td><a href="{% url "currency:source-update" source.id %}"> Edit </a></td>
    </tr>
    {% endfor %}

</table>

{% endblock main_content_list %}

app/currency/templates/source_update.html
{% extends "base.html" %}


{% block main_content %}

{{ massage }}
    
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Send </button>
</form>

<a href="{% url "currency:source-delete" form.instance.id %}"> Delete </a>

{% endblock main_content %}